[package]
name = "dss_rs_sys"
version = "0.1.0"
edition = "2021"
links = "dss_capi"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
bindgen = "0.60.1"
cmake = "0.1"
cmd_lib = "1.3.0"
